"""
Ensemble India Bot
A specialized strategy that incorporates a pre-trained XGBoost model 
for hourly predictions on Indian equities.
"""

from lumibot.strategies.strategy import Strategy
from lumibot.entities import Asset
import joblib
import pandas as pd
import pandas_ta as ta
import os
import google.generativeai as genai

class EnsembleTrader(Strategy):
    """
    Ensemble AI/ML Strategy loading an external XGBoost model.
    """

    def initialize(self):
        # Trade on hourly candles to avoid minute-level noise
        self.sleeptime = "1H"
        
        # Load the pre-trained machine learning model
        try:
            self.model = joblib.load("nifty_xgb_model.joblib")
            self.log_message("[EnsembleTrader] Model loaded successfully.", color="green")
        except FileNotFoundError:
            self.log_message(
                "[EnsembleTrader] nifty_xgb_model.joblib not found! Predictions will fail.", 
                color="red"
            )
            self.model = None

        # Set default daily macro bias and safety flags
        self.daily_macro_bias = "NEUTRAL"
        self.halt_trading = False

    def get_market_news(self):
        """Placeholder for fetching recent financial news headlines for the Indian Market."""
        return [
            "RBI expected to keep rates unchanged in upcoming policy meet.",
            "FPIs turn net sellers as valuation concerns rise in the short term.",
            "IT stocks rally tracking strong overnight gains in the US tech sector.",
            "Monsoon progress better than expected, aiding rural FMCG themes.",
            "Auto sector sales hit record highs ahead of the festive season."
        ]

    def before_market_opens(self):
        """
        Runs once per day before the market opens to set the daily statistical bias using Gemini.
        """
        self.halt_trading = False
        self.starting_portfolio_value = self.get_portfolio_value()
        
        gemini_api_key = os.getenv("GEMINI_API_KEY")
        if not gemini_api_key:
            self.log_message("[EnsembleTrader] GEMINI_API_KEY not set. Defaulting macro bias to NEUTRAL.", color="yellow")
            self.daily_macro_bias = "NEUTRAL"
            return
            
        genai.configure(api_key=gemini_api_key)
        model = genai.GenerativeModel("gemini-2.5-flash")
        
        headlines = self.get_market_news()
        news_text = "\n".join(f"- {h}" for h in headlines)
        
        prompt = (
            f"You are a ruthless hedge fund risk manager. Read these headlines:\n"
            f"{news_text}\n\n"
            f"What is the overall macro sentiment for the Indian market today? "
            f"You must reply with exactly one word: BULLISH, BEARISH, or NEUTRAL. No other text."
        )
        
        try:
            response = model.generate_content(prompt)
            bias = response.text.strip().upper()
            
            # Simple validation to ensure clean output
            if bias in ["BULLISH", "BEARISH", "NEUTRAL"]:
                self.daily_macro_bias = bias
            else:
                self.log_message(f"[EnsembleTrader] Unrecognized Gemini output: '{bias}'. Reverting to NEUTRAL.", color="yellow")
                self.daily_macro_bias = "NEUTRAL"
        except Exception as e:
            self.log_message(f"[EnsembleTrader] Error fetching Gemini macro sentiment: {e}", color="red")
            self.daily_macro_bias = "NEUTRAL"
            
        self.log_message(f"Daily Macro Bias set by Gemini: {self.daily_macro_bias}", color="cyan")

    def _get_ml_prediction(self, asset):
        """
        Calculates required features via pandas_ta and runs the XGBoost model 
        on the most recent bar to predict the next move.
        
        Returns:
            int: 1 for Buy, 0 for Do Nothing/Sell.
        """
        if self.model is None:
            self.log_message("Cannot predict; model is not loaded.", color="red")
            return 0

        # Fetch the last 50 hourly bars
        bars = self.get_historical_prices(asset, 50, "day")
        if bars is None or len(bars.df) < 35:
            self.log_message(f"Not enough data to calculate features for {asset.symbol}", color="yellow")
            return 0

        # Convert to pandas DataFrame
        df = bars.df.copy()

        # Calculate exact features the model was trained on
        # 1. 14-period RSI
        df.ta.rsi(length=14, append=True)

        # 2. MACD (12, 26, 9)
        # pandas_ta MACD by default uses fast=12, slow=26, signal=9.
        # It creates columns: MACD_12_26_9, MACDh_12_26_9 (histogram), MACDs_12_26_9 (signal)
        df.ta.macd(fast=12, slow=26, signal=9, append=True)

        # 3. 14-period ATR
        df.ta.atr(length=14, append=True)

        # Drop NaN values generated by indicator windows
        df.dropna(inplace=True)

        if df.empty:
            return 0

        # Extract the most recent row of these specific features
        # Assuming the model was explicitly trained on the core MACD output line, RSI, and ATR.
        feature_columns = ["RSI_14", "MACD_12_26_9", "ATRr_14"]
        
        # Guard check in case columns are named slightly differently by pandas_ta
        missing_cols = [c for c in feature_columns if c not in df.columns]
        if missing_cols:
            self.log_message(f"Missing expected pandas_ta columns: {missing_cols}", color="red")
            return 0

        latest_features = df[feature_columns].iloc[-1:]

        # Run inference
        try:
            prediction = self.model.predict(latest_features)
            # Extracted single integer prediction (1 or 0)
            return int(prediction[0])
        except Exception as e:
            self.log_message(f"Error generating ML prediction: {e}", color="red")
            return 0

    def on_trading_iteration(self):
        """
        Core iteration loop checking the ensemble logic.
        Executes strictly on the intersection of the ML model and LLM macro bias.
        """
        if getattr(self, "halt_trading", False):
            return

        # Hard Circuit Breaker
        current_portfolio_value = self.get_portfolio_value()
        if hasattr(self, "starting_portfolio_value") and self.starting_portfolio_value > 0:
            drop_amount = self.starting_portfolio_value - current_portfolio_value
            drop_pct = drop_amount / self.starting_portfolio_value
            if drop_pct > 0.02:
                self.log_message(
                    f"CRITICAL: Portfolio dropped by >2% ({drop_pct:.2%}). "
                    "Halting trading and selling all.", 
                    color="red"
                )
                self.sell_all()
                self.halt_trading = True
                return

        # Iterate through the universe
        for symbol in self.universe:
            asset = Asset(symbol=symbol, asset_type="stock" if ".NS" in symbol or ".BO" in symbol else "index")

            # Get ML prediction
            ml_signal = self._get_ml_prediction(asset)

            # The Ensemble Logic
            # In backtest we allow Neutral bias, in live we require Bullish
            is_bullish = self.daily_macro_bias == "BULLISH"
            if self.is_backtesting and self.daily_macro_bias == "NEUTRAL":
                is_bullish = True

            if ml_signal == 1 and is_bullish:
                # Check if we already have an open position
                position = self.get_position(asset)
                
                if position is None or position.quantity == 0:
                    # Calculate the current ATR value from historical data
                    bars = self.get_historical_prices(asset, 20, "day")
                    if bars is not None and len(bars.df) >= 15:
                        df = bars.df.copy()
                        df.ta.atr(length=14, append=True)
                        
                        if "ATRr_14" in df.columns:
                            current_atr = float(df["ATRr_14"].iloc[-1])
                            current_price = float(self.get_last_price(asset))
                            
                            # Bracket Order Config
                            stop_loss_price = current_price - (1.5 * current_atr)
                            take_profit_price = current_price + (3.0 * current_atr)
                            
                            # Place order
                            order = self.create_order(
                                asset=asset,
                                quantity=1,  # Example static quantity
                                side="buy",
                                take_profit_price=take_profit_price,
                                stop_loss_price=stop_loss_price,
                                type="market"
                            )
                            self.submit_order(order)
                            self.log_message(f"Ensemble BUY executed for {asset.symbol}. SL: {stop_loss_price:.2f}, TP: {take_profit_price:.2f}", color="green")
                        else:
                            self.log_message("Failed to calculate ATR for bracket order. Skipping.", color="yellow")
                    else:
                        self.log_message("Insufficient data to calculate ATR. Skipping.", color="yellow")
            else:
                self.log_message("ML Signal triggered BUY, but vetoed by Gemini macro bias.", color="yellow")

if __name__ == '__main__':
    from datetime import datetime
    import os
    import pandas as pd
    from lumibot.backtesting import YahooDataBacktesting
    from lumibot.data_sources import PandasData
    from lumibot.entities import Asset

    # 1. Define the backtesting window
    backtest_start = datetime(2025, 1, 1)
    backtest_end = datetime(2025, 12, 31)

    # 2. Path to local CSV data (as requested)
    csv_path = "data/NIFTY 50_15minute.csv"

    # 3. Handle Data Source logic
    # LumiBot's .backtest() takes the CLASS and initializes it internally.
    datasource_class = YahooDataBacktesting
    pandas_data = None

    if os.path.exists(csv_path):
        print(f"Using local CSV data from: {csv_path}")
        datasource_class = PandasData
        # PandasData expects a DataFrame in the 'pandas_data' parameter
        pandas_data = pd.read_csv(csv_path)
    else:
        print(f"Local CSV {csv_path} not found. Falling back to Yahoo Finance for backtesting.")

    print("Starting Ensemble AI Backtest...")
    
    # 5. Run the backtest and print the tearsheet/statistics
    # We pass the class (datasource_class) and if it's Pandas, we pass the data.
    EnsembleTrader.backtest(
        datasource_class,
        backtesting_start=backtest_start,
        backtesting_end=backtest_end,
        budget=2500000,  # ₹25,00,000 starting balance
        quote_asset=Asset(symbol="INR", asset_type="forex"),
        pandas_data=pandas_data,
        show_plot=True,
        show_tearsheet=True,
        save_logfile=True,
        universe=["NIFTY"] # Use the symbol that matches our CSV
    )
    
    print("Backtest Run Completed!")
